language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
addons:
  firefox: "45.0"
  apt:
    update: true
    packages:
      - net-tools
      - mplayer
      - python-gobject
      - python-setuptools
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
before_script:
  - wget --no-check-certificate "https://download.cpy.re/ffmpeg/ffmpeg-release-4.0.3-64bit-static.tar.xz"
  - tar xf ffmpeg-release-4.0.3-64bit-static.tar.xz
  - sudo cp ffmpeg-*-64bit-static/{ffmpeg,ffprobe,ffserver} /usr/bin
  - mkdir -p ~/.screenly ~/.config/uzbl/ ~/screenly_assets
  - cp ansible/roles/screenly/files/uzbl-config ~/.config/uzbl/config-screenly
  - cp ansible/roles/screenly/files/screenly.conf ~/.screenly/
  - cp ansible/roles/screenly/files/screenly.db ~/.screenly/
  - cp ansible/roles/screenly/files/screenly_utils.sh /tmp/screenly_utils.sh
  - echo -e "[local]\nlocalhost ansible_connection=local" > ansible/localhost
  - curl https://www.screenly.io/upload/ose-logo.png > /tmp/image.png
  - curl https://www.screenly.io/upload/ose-logo.png > ~/screenly_assets/image.tmp
  - curl https://www.screenly.io/upload/big_buck_bunny_720p_10mb.flv > /tmp/video.flv
  - cp tests/assets/asset.mov /tmp/asset.mov
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sudo cp tests/config/ffserver.conf /etc/ffserver.conf
  - /usr/bin/ffserver -f /etc/ffserver.conf &
  - sleep 3
  - python server.py &
  - sleep 3 # give xvfb some time to start

script:
  - find . ! -path "*/rtmplite/*" -name \*.py -exec pep8 --ignore=E402,E501,E731 {} +
  - nosetests -v -a '!fixme'
  - ansible-playbook --syntax-check -i ansible/localhost ansible/site.yml
  - python -m SimpleHTTPServer 8081 &
  - sleep 3
  - bash static/spec/runner.sh

sudo: false
dist: trusty
